
name: Deploy static content to Pages

on:

  push:
    branches: ["main"]



jobs:
  dotnet:
    name: dotnet Output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo dans la concole pour checkout
        run: echo OK
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Show .NET version
        run: dotnet --version
      - name: build project
        working-directory: ./app
        run: dotnet build
      - name: artefact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build
          path: ./app/bin/Debug/net9.0


  dockerhub:
    name: Dockerhub Output
    runs-on: ubuntu-latest
    needs: dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artefact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-build
          path: ./app/bin/Debug/net9.0
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker push build
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iia-devops:dotnet

  github-runner:
    name: Github runner 
    runs-on: self-hosted
    needs: dockerhub
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: docker compose up
        run: docker compose up -d --pull always --force-recreate --no-deps dotnet-app
        
