
name: Deploy static content to Pages

on:

  push:
    branches: ["main"]



jobs:
  dotnet:
    name: dotnet Output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo dans la concole pour checkout
        run: echo OK
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Show .NET version
        run: dotnet --version
      - name: build project
        working-directory: ./app
        run: dotnet build


  dockerhub:
    name: Dockerhub Output
    runs-on: ubuntu-latest
    needs: dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker push build
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iia-devops:dotnet
