
name: Deploy static content to Pages

on:

  push:
    branches: ["main"]



jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo dans la concole pour checkout
        run: echo OK
  dotnet:
    name: dotnet Output
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Show .NET version
        run: dotnet --version
      - name: r√©pertoire de travail
        run: workdir ./app
      - name: build project
        run: dotnet build
      - name: echo dans la concole pour dotnet
        run: echo build OK